# Generated by Django 3.0.8 on 2021-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='bukti/'),
        ),
    ]
